# Generated by Django 6.0.2 on 2026-02-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_fullname_customuser_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.IntegerField(choices=[(0, 'user'), (1, 'reception'), (2, 'doctor'), (3, 'admin')], default=0),
        ),
    ]
