# Generated by Django 6.0.2 on 2026-02-18 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.IntegerField(choices=[(0, 'user'), (1, 'reception'), (2, 'doctor'), (3, 'admin')], default=3),
        ),
    ]
