# Generated by Django 6.0.2 on 2026-02-19 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_bio_alter_customuser_status_and_more'),
        ('hospitals', '0002_remove_department_hospital_hospital_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='director',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_hospital', to='accounts.director'),
        ),
    ]
